^ Welcome to C'Dent

C'Dent is a new programming language for writing portable modules. It is based on the computer programming principle known as H.O.P.E. (Hack Once, Please Everyone)

When you write a module in C'Dent, you can use it in a dozen different programming languages. For instance, you could write a module in Python and use it in JavaScript, or you ould write a module in JavaScript and use it in Perl 6, Ruby or Java.

