^ C'Dent News

This is the latest happenings in the world of C'Dent. (RSS coming soon...)

----

^^^ March 22, 2010

Ingy will be presenting a talk entitled "Please Check Your Guns at the Door /C'Dent, the Acmeism and Everyone/"<http://osdc.tw/2010/03/schedule_please_check_your_gun.html> at the "2010 Open Source Developers' Conference Taiwan"<http://osdc.tw/> on April 25th in 台北. 

----

^^^ March 21, 2010

Ingy will be presenting a talk on C'Dent at the "Seattle Python Interest Group"<http://www.seapig.org/>, on Thursday, April 8th.

